<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <RootNamespace>InterviewApi.Tests</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.8.0" />
    <PackageReference Include="xunit" Version="2.5.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.5.3" />
    <PackageReference Include="coverlet.collector" Version="6.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\InterviewApi\InterviewApi.csproj" />
    <ProjectReference Include="..\InterviewApi.Application\InterviewApi.Application.csproj" />
    <ProjectReference Include="..\InterviewApi.Domain\InterviewApi.Domain.csproj" />
    <ProjectReference Include="..\InterviewApi.Infrastructure\InterviewApi.Infrastructure.csproj" />
  </ItemGroup>

</Project>
